"""Render the soak page from the published results, and refuse a hand edit.

`docs/production/soak.mdx` is a **render**, never written by hand. Every number on it comes
from `research/soak/results/*.json`, which the maintainer publishes by committing a run, and
until one exists the page says so in those words and shows no table.

    python tools/docs_audit/render_soak.py --write
    python tools/docs_audit/render_soak.py --check

Two sentences on that page are the reason it is generated rather than written.

**The duration is the measured one.** `SPEC-v0.6.md` §8.1's week is calendar time and does not
compress; the harness prints how long the run actually lasted and is not allowed to decide
whether that was long enough. So the page prints the same figure and says, in the same
paragraph, that `ROADMAP.md`'s exit criterion is not met by it. A page that said "soaked" and
left the clock out would be the flattering half of a true sentence.

**`exit_criterion_met` in the JSON is about the ambiguity count alone.** It is the harness
answering the only question a harness may answer — *did an `AMBIGUOUS` appear that I did not
cause?* — and it is not the release gate. The page names the field and says what it covers,
because a reader who finds `true` in the results file and no explanation will read it as the
gate it is not.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from _files import REPO_ROOT, relative

RESULTS = REPO_ROOT / "research" / "soak" / "results"
TARGET = REPO_ROOT / "docs" / "production" / "soak.mdx"
MARKER = (
    "generated by tools/docs_audit/render_soak.py from research/soak/results/ — "
    "publish a run, do not edit this page"
)
NO_RESULTS = "No published results yet."
CRITERION_DAYS = 7


def latest() -> tuple[Path, dict] | None:
    """The most recently published run, or `None` when none has been."""
    files = sorted(RESULTS.glob("*.json")) if RESULTS.is_dir() else []
    if not files:
        return None
    return files[-1], json.loads(files[-1].read_text(encoding="utf-8"))


def _table(run: dict) -> list[str]:
    ambiguous = run["ambiguous"]
    return [
        "| | |",
        "|---|---|",
        f"| Ran for | {run['elapsed_human']} ({run['started_at'][:16].replace('T', ' ')}Z → "
        f"{run['ended_at'][:16].replace('T', ' ')}Z) |",
        f"| Backend | {run['backend']} |",
        f"| Actions attempted | {run['actions']:,} |",
        f"| Ended `AMBIGUOUS` | {ambiguous:,} |",
        f"| Explained by a recorded injection | {run['explained']:,} |",
        f"| **Unattributed** | **{run['unexplained']:,}** |",
        f"| Positive control fired | {'yes' if run['positive_control_fired'] else 'no'} |",
    ]


def render() -> str:
    found = latest()
    lines = [
        "---",
        'title: "The soak, and what it does not establish"',
        'description: "One published run against a real Postgres: how long it lasted, how many '
        'actions it attempted, and how many ambiguous outcomes it could not attribute."',
        "---",
        "",
        "{/* " + MARKER + " */}",
        "",
    ]
    if found is None:
        lines += [
            f"**{NO_RESULTS}** The harness is in the repository and this page renders from what",
            "it produces, so there is nothing here until a run is committed. Nothing on this",
            "site claims a soak result in the meantime.",
            "",
        ]
    else:
        path, run = found
        lines += [
            "A soak asks one question, and it is not a performance question: **does an",
            "`AMBIGUOUS` outcome ever appear that the harness did not cause?** Everything in the",
            "run exists to make an unattributed ambiguity visible rather than rare. Here is the",
            "one published run.",
            "",
            *_table(run),
            "",
            f"The table is [`{relative(path)}`]"
            f"(https://github.com/CTRLRun/ctrlrun/blob/main/{relative(path)}), rendered.",
            "",
            "## What that is evidence of",
            "",
            f"Across {run['actions']:,} attempts, every `AMBIGUOUS` the store held at the end had",
            "a ledger entry written **before** the failure that produced it. Nothing became",
            "ambiguous that the harness did not make ambiguous. The positive control fired, so",
            "the run was capable of saying otherwise: a short control phase injects an ambiguity",
            "it deliberately does not record, and the classifier has to report it. A run whose",
            "control did not fire is not a result, and the table says which happened.",
            "",
            "**Unexplained is defined before the run starts**, or the question is unfalsifiable.",
            "An `AMBIGUOUS` whose attempt has a recorded injection is explained; one with no",
            "corresponding injection is unattributed. It is keyed on the attempt and never on the",
            "effect key alone, because one key may be attempted more than once and an injection",
            "against the first attempt says nothing about the second.",
            "",
            "## What it is not evidence of",
            "",
            "**`ROADMAP.md`'s exit criterion, which is a soak of at least one week.** This ran",
            f"for {run['elapsed_human']}. A week of calendar time does not compress, and a larger",
            "action count is not a substitute for it: a ten-hour run would meet the criterion no",
            "better, it would put a bigger number beside something still unmet. The criterion is",
            "recorded in the roadmap as **not met**, and that is the honest state of it.",
            "",
            "`exit_criterion_met: true` in the results file is about the **ambiguity count** and",
            "nothing else. That is all the harness is allowed to decide; the clock is reported",
            "and left to a person to read.",
            "",
            "## What this does not do",
            "",
            "- **It is not a load test.** The throughput is a by-product, nothing here is tuned",
            "  for it, and no number on this page is a performance claim.",
            "- **It does not size the receipt chain.** Most of these actions are denied or",
            "  refused by policy before a receipt is written, so the run says little about the",
            "  one-row head every receipt write serializes on. [Postgres](/postgres) describes",
            "  that ceiling; this run does not measure it.",
            "- **It does not exercise a partition or a second host.** That is the cross-host",
            "  suite, and [how reservation works](/production/how-reservation-works) says which",
            "  of those were actually run.",
            "- **It says nothing about the receipt chain's integrity.**",
            "  [Receipt integrity](/production/receipt-integrity) is that.",
            "",
            "## Run it yourself",
            "",
            "```bash",
            'python research/soak/run.py --minutes 20 --postgres "$CTRLRUN_STORE_URL" --out soak.json',
            "```",
            "",
            "Four worker threads, one store each, into a schema created for the run and dropped",
            "after it. The injection mix is 70% clean, 10% executor timeout, 10% unknown",
            "exception, 8% `NotExecuted`, and 2% a lease short enough to lapse mid-execution.",
            "",
            "**Verified by** `T178` — the harness detects an injected `AMBIGUOUS`, which is the",
            "positive control this whole page rests on. See also `T160` for what an expired lease",
            "does and does not free.",
            "",
        ]
    lines += [
        "## Next",
        "",
        "- [Run it in production](/production/index): the section this belongs to.",
        "- [Recovery after a crash](/production/recovery): what survives a restart, and what does not.",
        "- [Get started](/get-started/quickstart) · [Why](/why).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    text = render()
    if arguments.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text, encoding="utf-8")
        print(f"wrote {relative(TARGET)}")
    if arguments.check or not arguments.write:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"DRIFT {relative(TARGET)} differs from the published results; run --write")
            return 1
        print(f"soak page: {relative(TARGET)} matches the published results")
    return 0


if __name__ == "__main__":
    sys.exit(main())
